spring.application.name=staff

server.port=8084
#ubicación de la BD a la que nos conectaremos
spring.datasource.url=jdbc:mysql://localhost:8084/staff_db
#usuario y clave para conectarnos a la BD
spring.datasource.username=root
spring.datasource.password=
#driver a usar segun la BD a conectar
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#dialecto, lenguaje de transformación para comunicarnos con la BD
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#JPA
#metodo para la creacion de las tablas
#update: si no existen las tblas las crea y si existen verifica si hay que hacer alguna mod
spring.jpa.hibernate.ddl-auto=update
#propiedades para mostrar las sentencias sql que se ejecutan en el microservicio internamente
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true